print ('========================')
print ('1-pyClass1') # String 
print ('========================')
print ("2-pyClass1-2")
print ('========================')
print (2022) #int
print ('========================')
print (3- 2022 + 2000)
print ('========================')
print ('5 + 5=')
print ('========================')
print ('Python Class1')
print ('========================')
print ('python class1 2022')
print ('========================')
print ('one','tow','three')
print ('========================')
print ("one","tow","three")
print ('========================')
print ('A++ |', 'Mongo |','Dart |','ruby |')
print ('====use==sep=""=========')
print ("one","tow","three", sep="|")
print ('========================')
print ("one","tow","three", sep="#")
print ('========================')
print ("one","tow","three", sep="*")
print ('========================')
print ("one","tow","three", sep="$")
print ('========================')
print ("one","tow","three", sep="::")
print ('========================')
print ("one","tow","three", sep=" and ")
print ('========================')
print ("one","tow","three", sep="or")
print ('========================')
print ("one","tow","three", sep=" or")
print ('========================')
print ("one","tow","three", sep="or ")
print ('========================')
print ("one","tow","three","...", sep=" or ")
print ('========================')
print (10*'10pythonClass1')
print ('========================')
print (6*' 6pythonClass1')
print ('========================')
print (8*' 8pythonClass1 ')
print ('========================')
print (10*'10pythonClass1:10new_line \n')
print ('========================')
print (True)
print ('------------------------')
print (False)
print ('========================')
print ('Python\nClass') #\n = next to new line 
print ('------------------------')
print ('Python\tClass') #\t = tap 4 spaces
print ('------------------------')
'''
comments
'''


